castledio/castled

- .bumpversion.cfg
- .env
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
> Bumping Castled version from 0.1.5-alpha to 0.1.6-alpha

- .bumpversion.cfg
- .env
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
> Bumping Castled version from 0.1.6-alpha to 0.1.7-alpha

- .bumpversion.cfg
- .env
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
> Bumping Castled version from 0.1.7-alpha to 0.1.8-alpha

- .bumpversion.cfg
- .env
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
> Bumping Castled version from 0.1.8-alpha to 0.1.9-alpha

- .bumpversion.cfg
- .env
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
> Bumping Castled version from 0.1.9-alpha to 0.1.10-alpha

- .bumpversion.cfg
- .env
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
> Bumping Castled version from 0.1.10-alpha to 0.1.11-alpha

- .bumpversion.cfg
- .env
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
> Bumping Castled version from 0.1.11-alpha to 0.1.12-alpha

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/Dockerfile
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.1.16-alpha to 0.1.17-alpha

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/Dockerfile
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.1.17-alpha to 0.1.18-alpha

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/Dockerfile
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.1.22-alpha to 0.1.23-alpha

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/Dockerfile
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.1.23-alpha to 0.1.24-alpha

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.1.26-alpha to 0.1.27-alpha

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.1.27-alpha to 0.1.28-alpha

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.1.28-alpha to 0.1.29-alpha

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.1.32-alpha to 0.1.33-alpha

- webapp/app/common/dtos/TeamDTO.ts
- webapp/app/services/authService.ts
- webapp/pages/activate-user/index.tsx
- webapp/pages/auth/register.tsx
- webapp/pages/settings/members.tsx
@franklinio Created this new branch for team members invitation as discussed. 
Pl review and release to test. Adding screenshots for reference.
> Team members support

- docs/docs/deploying-castled/_category_.json
- docs/docs/getting-started/_category_.json
> warehouse doc correction 

- container/src/main/java/io/castled/CastledModule.java
- container/src/main/java/io/castled/models/RedisConfig.java
> feat: redis add password support

- README.md
This PR is to correct spelling.
> Correct Spelling Error

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.2.16-alpha to 0.2.17-alpha

- webapp/app/components/pipeline/PipelineRunView.tsx
- webapp/pages/auth/register.tsx
- webapp/pages/pipelines/[pipelineId].tsx
- webapp/styles/colors.scss
- webapp/styles/main.scss
> All changes done by Vishal in Jan

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.2.17-alpha to 0.2.18-alpha

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.2.18-alpha to 0.2.19-alpha

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.2.19-alpha to 0.2.20-alpha

- .bumpversion.cfg
- .env
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.2.20-alpha to 0.2.21-alpha

- charts/castled/templates/webapp/ingress.yaml
svcPort was referring to service.port instead of webapp.service.port
> Fix ingress svcPort

- .bumpversion.cfg
- .env
- charts/castled/values.yaml
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.2.22-alpha to 0.2.23-alpha

- webapp/app/components/forminputs/InputRadioButton.tsx
Added input text description with styles as given on CAS-174 ticket. 
Also, are we using any custom radio libraries to make it look exactly that.
Kindly check and let me know if you have any suggestions for the same.
Looks something like this:
> input text box added description with styles

- webapp/app/components/forminputs/InputRadioButton.tsx
- webapp/styles/light.scss
Moved styles of all `.description` classes to scss light file.
> moved styles inline to scss - class .description

- webapp/app/components/forminputs/InputRadioButton.tsx
- webapp/styles/light.scss
> Revert "moved styles inline to scss - class .description"

- .bumpversion.cfg
- .env
- charts/castled/values.yaml
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.2.23-alpha to 0.2.24-alpha

- .bumpversion.cfg
- .env
- charts/castled/values.yaml
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.2.25-alpha to 0.2.26-alpha

- .bumpversion.cfg
- .env
- charts/castled/values.yaml
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.2.29-alpha to 0.2.30-alpha

- .bumpversion.cfg
- .env
- charts/castled/values.yaml
- commons/pom.xml
- connectors/pom.xml
- container/pom.xml
- jarvis/pom.xml
- kube/overlays/cloud/.env
- kube/overlays/cloud/kustomization.yaml
- kube/overlays/community/.env
- kube/overlays/community/kustomization.yaml
- pom.xml
> Bumping Castled version from 0.2.37-alpha to 0.2.38-alpha

- webapp/app/components/pipeline/PipelineSettingsForm.tsx
- webapp/app/components/pipeline/step2destination/PipelineWizardDestination.tsx
- webapp/app/components/pipeline/step3mapping/PipelineMapping.tsx
- webapp/app/components/pipeline/step3mapping/components/Layouts/AdditionalFields.tsx
- webapp/app/components/pipeline/step3mapping/components/Layouts/DestinationFieldRows.tsx
- webapp/app/components/pipeline/step3mapping/components/MappingDestinationFields.tsx
- webapp/app/components/pipeline/step3mapping/components/MappingImportantFields.tsx
- webapp/app/components/pipeline/step3mapping/components/MappingMiscellaneousFields.tsx
- webapp/app/components/pipeline/step3mapping/components/MappingPrimaryKeyFields.tsx
- webapp/app/components/pipeline/step3mapping/types/componentTypes.ts
- webapp/app/components/pipeline/step3mapping/utils/MappingAutoFill.ts
Users now able to persist their input across the lifecycle.
> State persist mapping

- webapp/app/components/pipeline/step3mapping/components/Layouts/WarehouseColumn.tsx
- webapp/app/components/pipeline/step3mapping/components/MappingMiscellaneousFields.tsx
- webapp/pages/auth/login.tsx
- webapp/pages/auth/logout.tsx
Test Name | Tested on Enterprise?(Yes/No)
-- | --
Clear DB:DROP DATABASE DB_NAME;CREATE DATABASE DB_NAME; | Yes
Login |  
Can you sign-in? (IS_OSS=true) in .env | Not Applicable
Can you sign in? (IS_OSS=false) in .env | Yes
Can you log out? (IS_OSS=false) in .env | Yes
Welcome |  
Can you see two buttons?(Create using Demo & Own warehouse) | Yes
Can you see the “steps left” on each button? | Yes
Does clicking on both buttons open the onboarding steps dropdown? (For demo 3rd step, For own 1st step will open) | Yes
Does clicking on buttons in the dropdown, redirects us to respective screens)E.g. "+ Add App" should redirect to the "Create Destination" page. | Yes
Can you go back using the "Go Back" button | Yes
Does clicking on one dropdown close the other? | Yes
Warehouse |  
Click on the …
> Gsheets pk mapping fix

- webapp/app/components/onboarding/WelcomePopup.tsx
- webapp/pages/activate-user/index.tsx
- webapp/pages/auth/login.tsx
- webapp/pages/auth/register.tsx
- webapp/pages/auth/signup.tsx
redesigned
- login page
- register page
- signup page
- authenticate-user page
- Added signup button to login forms
- improve design consistency
> registration flow redesign

- webapp/pages/auth/login.tsx
Previous behavior : Landing page comes out as it is OSS landing page. that is without user details , settings menu and the landing page without demo details. On page refresh everything appears.
Fixed behavior : Show the landing page which should be coming when we login along with both demo and own warehouse option in welcome page , settings menu and the user details.
[https://castledio.atlassian.net/browse/CAS-233](https://castledio.atlassian.net/browse/CAS-233)
> CAS-233 - Sign in inconsistency when clicked on sign in from the website for an already logged in user

- webapp/app/components/forminputs/CodeInput.tsx
- webapp/app/components/forminputs/InputField.tsx
- webapp/app/components/model/CreateModel.tsx
- webapp/app/components/model/ModelQueryView.tsx
- webapp/app/components/pipeline/PipelineMappingView.tsx
- webapp/app/components/pipeline/PipelineMappingViewRestApi.tsx
- webapp/app/components/pipeline/step1source/WarehouseModel.tsx
- webapp/package.json
- webapp/pages/pipelines/[pipelineId].tsx
- webapp/yarn.lock
Features:
1. Auto code completion
2. Light and dark mode
3. Line numbering
4. Syntax highlighting
:white_check_mark: Done
> CAS-237 - SQL code editor across the app
